version: 1.0.{build}
image: Visual Studio 2017
clone_depth: 1
build_script:
- cmd: >-
    dotnet restore

    dotnet build
test_script:
- cmd: dotnet test --filter TestCategory!=DatabaseIntegration
deploy: off