version: "3.7"
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "80"
    networks:
      - network
  db:
    image: "microsoft/mssql-server-windows-developer:2017-CU3"
    environment:
        SA_PASSWORD: "PoTracker001"
        ACCEPT_EULA: "Y"
    # Expose connectivity to host machine for debugging purposes
    ports:
      - "1433:1433"